#!/usr/bin/env python3
import sys
import os
from pytube import YouTube

# Downloads YouTube Video to directory this was called from
urls = sys.argv[1:]

for url in urls:
    yt = YouTube(url)
    yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first().download()

